### ISSUE TITLE
Check reviews requests reviews on draft PRs

### ISSUE THREAD

**Issue by TriplEight** [paritytech/pr-custom-review#90] opened 2022-04-20 10:01 UTC
_@coderobe [wrote](https://matrix.to/#/!gJeGMHCcDoIwsHIJri:matrix.parity.io/$uKIRL9HWAENJTkBwBoAN9Pm-1Dv3J-SzdzpZ00i2iKk?via=matrix.parity.io)_

> The "Check reviews" step currently automatically requests reviews on draft PRs, i think the correct behaviour would be to only request review once the draft is converted to a non-draft PR.
To avoid creating noise for the reviewers for draft PRs that are not intended to be merged anyways and stuff that's far from ready

**Comment by joao-paulo-parity** [comment] 2022-04-20 11:52
I wouldn't say this is a bug because it currently works as intended. The problem is that we never considered this kind of request.

**Comment by joao-paulo-parity** [comment] 2022-04-28 10:58
Closing because https://github.com/paritytech/substrate/pull/11248 and https://github.com/paritytech/polkadot/pull/5356 and https://github.com/paritytech/cumulus/pull/1188 all got merged.

**Closed by joao-paulo-parity** 2022-04-28 10:58 UTC
Labels: enhancement
